name: rutoken_flutter
description: Обнаружение устройств "Рутокен"
version: 0.0.1
homepage: https://github.com/qscr/rutoken_flutter

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.a2soft.rutoken_flutter
        pluginClass: RutokenFlutterPlugin
      ios:
        pluginClass: RutokenFlutterPlugin